### PR TITLE
Add fixedwidth formatting to error display

### PR DESCRIPTION
**Pull request by joshbode**
use triple-backticks to wrap exception display

### CODE REVIEW

**Comment by keitakurita** [comment]
Thanks for the PR! Could you show an example of how the output would change given your feature?

**Comment by joshbode** [comment]
Sorry - that would have been a good thing to include :)

It'll look like:

> Error while abc:
> ```ZeroDivisionError('division by zero',)```

rather than:

> Error while abc: ZeroDivisionError('division by zero',)

Will add a screenshot

**Comment by joshbode** [comment]
image

**Comment by joshbode** [comment]
Was thinking an option to display the traceback might be good to add in the future, however, you can just go to the actual notebook

**Comment by keitakurita** [comment]
Ah, I see! Got it, thanks!

**Comment by keitakurita** [comment]
Displaying the traceback is an idea I also had in the past, but in my experience, it makes the message too cluttered. You'll need to go to the notebook for detailed debugging anyway, so I currently think that the error is probably enough. I could be convinced otherwise though.

**Comment by joshbode** [comment]
Thanks!

**Pull request merged**
